version: '3.9'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: satellitor_db
    environment:
      POSTGRES_DB: satellitor
      POSTGRES_USER: satellitor
      POSTGRES_PASSWORD: satellitor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U satellitor -d satellitor"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: satellitor_web
    command: sh -c "python Satellitor/manage.py migrate && python Satellitor/create_superuser.py && python Satellitor/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: satellitor
      POSTGRES_USER: satellitor
      POSTGRES_PASSWORD: satellitor
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin112
      DJANGO_SUPERUSER_EMAIL: admin@outlook.com
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:


