# Generated by Django 5.2.5 on 2025-09-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
