# Generated by Django 5.2.5 on 2025-09-04 10:36

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True, verbose_name='Crop Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['crop_name'],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Land Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soil Type')),
                ('irrigation_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Irrigation Type')),
                ('status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Boundary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CropInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(verbose_name='Planting Date')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Harvest Date')),
                ('season', models.CharField(blank=True, choices=[('Winter', 'شتوي'), ('Summer', 'صيفي'), ('Nile', 'نيل'), ('Spring', 'ربيعي'), ('Autumn', 'خريفي')], max_length=20, null=True, verbose_name='Season')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='farmapp.crops', verbose_name='Crop')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_instances', to='farmapp.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Crop Instance',
                'verbose_name_plural': 'Crop Instances',
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='LandSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Size Value')),
                ('unit', models.CharField(choices=[('feddan', 'Feddan'), ('acre', 'Acre'), ('hectare', 'Hectare'), ('square_meter', 'Square Meter')], default='feddan', max_length=20, verbose_name='Unit')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='farmapp.land')),
            ],
            options={
                'verbose_name': 'Land Size',
                'verbose_name_plural': 'Land Sizes',
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(choices=[('B01', 'Band 1 - Coastal Aerosol'), ('B02', 'Band 2 - Blue'), ('B03', 'Band 3 - Green'), ('B04', 'Band 4 - Red'), ('B05', 'Band 5 - Red Edge 1'), ('B06', 'Band 6 - Red Edge 2'), ('B07', 'Band 7 - Red Edge 3'), ('B08', 'Band 8 - NIR'), ('B8A', 'Band 8A - Narrow NIR'), ('B09', 'Band 9 - Water Vapour'), ('B11', 'Band 11 - SWIR 1'), ('B12', 'Band 12 - SWIR 2')], max_length=4, verbose_name='Band Name')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('file_path', models.CharField(max_length=500, verbose_name='GeoTIFF File Path')),
                ('resolution_m', models.PositiveIntegerField(verbose_name='Resolution (m)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='farmapp.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Satellite Image',
                'verbose_name_plural': 'Satellite Images',
                'ordering': ['-acquisition_date', 'band_name'],
            },
        ),
        migrations.CreateModel(
            name='VegetationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('NDVI', 'NDVI - Normalized Difference Vegetation Index'), ('NDRE', 'NDRE - Normalized Difference Red Edge'), ('NDMI', 'NDMI - Normalized Difference Moisture Index')], max_length=10, verbose_name='Index Type')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('value_raster_path', models.CharField(max_length=500, verbose_name='Index GeoTIFF File Path')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('mean_value', models.FloatField(blank=True, null=True, verbose_name='Mean')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_indices', to='farmapp.land', verbose_name='Land')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indices', to='farmapp.satelliteimage', verbose_name='Source Satellite Image')),
            ],
            options={
                'verbose_name': 'Vegetation Index',
                'verbose_name_plural': 'Vegetation Indices',
                'ordering': ['-acquisition_date', 'index_type'],
            },
        ),
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20, verbose_name='Season Name')),
                ('start_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Start Month')),
                ('end_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='End Month')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='farmapp.crops', verbose_name='Crop')),
            ],
            options={
                'verbose_name': 'Crop Calendar',
                'verbose_name_plural': 'Crop Calendars',
                'ordering': ['crop', 'start_month'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_month__gte', 1), ('start_month__lte', 12)), name='start_month_valid_range'), models.CheckConstraint(condition=models.Q(('end_month__gte', 1), ('end_month__lte', 12)), name='end_month_valid_range'), models.CheckConstraint(condition=models.Q(('end_month__gte', models.F('start_month'))), name='end_month_after_start_month'), models.UniqueConstraint(fields=('crop', 'season_name'), name='uniq_crop_season_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='land',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_user_land_name'),
        ),
        migrations.AddConstraint(
            model_name='cropinstances',
            constraint=models.UniqueConstraint(fields=('land', 'crop', 'planting_date'), name='uniq_land_crop_planting'),
        ),
        migrations.AddConstraint(
            model_name='satelliteimage',
            constraint=models.UniqueConstraint(fields=('land', 'band_name', 'acquisition_date'), name='uniq_land_band_date'),
        ),
        migrations.AddConstraint(
            model_name='vegetationindex',
            constraint=models.UniqueConstraint(fields=('land', 'index_type', 'acquisition_date'), name='uniq_land_index_date'),
        ),
    ]
