# Generated by Django 5.2.5 on 2025-09-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropCalendar',
        ),
    ]
