# Generated by Django 5.2.5 on 2025-09-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_delete_cropcalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetationindex',
            name='source_image',
        ),
        migrations.RemoveField(
            model_name='vegetationindex',
            name='land',
        ),
        migrations.CreateModel(
            name='VegetationIndexSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('file_path', models.CharField(max_length=500, verbose_name='Multiband GeoTIFF Path')),
                ('stats', models.JSONField(default=dict, verbose_name='Index Stats')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veg_index_sets', to='farmapp.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Vegetation Index Set',
                'verbose_name_plural': 'Vegetation Index Sets',
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.DeleteModel(
            name='SatelliteImage',
        ),
        migrations.DeleteModel(
            name='VegetationIndex',
        ),
        migrations.AddConstraint(
            model_name='vegetationindexset',
            constraint=models.UniqueConstraint(fields=('land', 'acquisition_date'), name='uniq_land_indexset_date'),
        ),
    ]
