# Generated by Django 5.2.5 on 2025-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_remove_vegetationindex_source_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='sowing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sowing Date'),
        ),
    ]
