# Generated by Django 5.2.5 on 2025-09-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_land_sowing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='sowing_date',
        ),
    ]
