# Generated by Django 5.2.5 on 2025-09-11 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmapp', '0003_remove_vegetationindex_source_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold Alert'), ('anomaly', 'Anomaly Detection'), ('trend', 'Trend Analysis'), ('custom', 'Custom Script')], max_length=20, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity')),
                ('index_name', models.CharField(max_length=20, verbose_name='Index Name')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Threshold Value')),
                ('comparison_operator', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('eq', 'Equal'), ('ne', 'Not Equal')], default='lt', max_length=10, verbose_name='Comparison Operator')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notification_methods', models.JSONField(default=list, help_text="List of notification methods: ['email', 'sms', 'webhook']", verbose_name='Notification Methods')),
                ('custom_script', models.TextField(blank=True, verbose_name='Custom Script')),
                ('cooldown_hours', models.IntegerField(default=24, verbose_name='Cooldown Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='farmapp.land', verbose_name='Land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='triggered', max_length=20, verbose_name='Status')),
                ('severity', models.CharField(max_length=20, verbose_name='Severity')),
                ('index_name', models.CharField(max_length=20, verbose_name='Index Name')),
                ('index_value', models.FloatField(verbose_name='Index Value')),
                ('threshold_value', models.FloatField(verbose_name='Threshold Value')),
                ('comparison_operator', models.CharField(max_length=10, verbose_name='Comparison Operator')),
                ('message', models.TextField(verbose_name='Alert Message')),
                ('context_data', models.JSONField(default=dict, verbose_name='Context Data')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered At')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farmapp.land', verbose_name='Land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vegetation_index_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farmapp.vegetationindexset', verbose_name='Vegetation Index Set')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule', verbose_name='Alert Rule')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook'), ('push', 'Push Notification')], max_length=20, verbose_name='Type')),
                ('recipient', models.CharField(max_length=200, verbose_name='Recipient')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('response_data', models.JSONField(default=dict, verbose_name='Response Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert', verbose_name='Alert')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('land', 'name'), name='uniq_land_alert_rule_name'),
        ),
    ]
