# Generated by Django 5.2.5 on 2025-09-11 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('farmapp', '0003_remove_vegetationindex_source_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Scenario Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('scenario_type', models.CharField(choices=[('rapid_ndvi_drop', 'Rapid NDVI Drop (Acute Stress)'), ('spatial_anomaly', 'Spatial/Patchy Anomaly (Localized Problem)'), ('growth_stagnation', 'Stagnation During Growth (Expected Rise Not Happening)'), ('below_historical', 'Below Historical Percentile (Seasonal Anomaly/Drought)'), ('phenology_delay', 'Delay in Phenology (SOS/EOS Deviation)'), ('poor_emergence', 'Persistent Low NDVI After Sowing (Poor Emergence)'), ('trend_decline', 'Long-term Trend Decline (Chronic Degradation)')], max_length=50, verbose_name='Scenario Type')),
                ('parameters', models.JSONField(default=dict, verbose_name='Scenario Parameters')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('cooldown_hours', models.IntegerField(default=24, verbose_name='Cooldown Hours')),
                ('notification_methods', models.JSONField(default=list, verbose_name='Notification Methods')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_scenarios', to='farmapp.land', verbose_name='Land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Alert Scenario',
                'verbose_name_plural': 'Alert Scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='alerts.alertscenario')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertscenario',
            constraint=models.UniqueConstraint(fields=('land', 'name'), name='uniq_land_scenario_name'),
        ),
    ]
